apps/routine/urls.py
from django.urls import  path
from . import  views

app_name = "routine"

urlpatterns = [
    path("", views.RoutineList.as_view(), name="routine_list"),

    path("update-routine/<str:token>/", views.UpdateRoutine.as_view(), name="update_routine"),

    path("create-routine/", views.CreateRoutine.as_view(), name='create_routine'),

    path("delete-routine/<str:token>/", views.DeleteRoutine.as_view(), name="delete_routine"),


]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("account/",include("allauth.urls")),
    path("auth/",include("apps.accounts.urls")),

    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.jwt')),



    path("", include("apps.task.urls")),
    path("routine/", include("apps.routine.urls")),
    path("project/", include("apps.project.urls")),
]

apps/routine/models.py
from django.db import models
from task.models import Base


class Routine(Base):
    '''Routine model that inherits base model'''

    class Choises(models.TextChoices):
        once = ("o", "Once")
        daily = ("d", "Daily")
        mon_to_fri = ("m", "Mon To Fri")


    repeat = models.CharField(max_length=1, choices=Choises.choices, default=Choises.once)

    def __str__(self):
        return self.title

apps/routine/forms.py
from django import  forms
from routine.models import Routine

class RoutineForm(forms.ModelForm):
	class Meta:
		model = Routine
		fields = "__all__"

apps/api/v1/views/routine_views.py
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.db.models import Q
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, ListAPIView
from rest_framework.response import Response

import uuid

from api.v1.serializers import RoutineSerializer, RoutineCreateSerializer, RoutineDetailSerializer
from routine.models import Routine
from accounts.models import User

class RoutineView(ListAPIView):
    '''
        Show all routines
    '''
    model = Routine
    serializer_class = RoutineSerializer
    def get_queryset(self):
        owner = self.kwargs["owner"]
        object = Routine.objects.filter(Q(owner__token=owner))
        return object

class RoutineAdd(CreateAPIView):
    '''
        Create routine
    '''
    queryset = Routine.objects.all()
    serializer_class = RoutineCreateSerializer
    def create(self,request,owner):
        data = self.request.data
        serializer = RoutineCreateSerializer(data=data, partial=True)
        routine_owner = User.objects.get(token=owner)
        if serializer.is_valid():
            serializer = serializer.save(owner=routine_owner ,token=uuid.uuid4().hex.upper()[0:12])
            return JsonResponse({"token" : serializer.token})
        else:
            return JsonResponse({"error" : "sth is wrong with your information"})

class RoutineDetail(APIView):
    '''
        Your routine detail
    '''
    queryset = Routine.objects.all()
    serializer_class = RoutineDetailSerializer
    def get(self,request,owner,token):
        queryset = Routine.objects.filter(Q(token=token) & Q(owner__token=owner))
        serializer = RoutineDetailSerializer(queryset, many=True)
        return Response(serializer.data)

class RoutineDelete(APIView):
    '''
        Delete a Routine
    '''
    def get(self,request,token,owner):
        try:
            Routine.objects.filter(Q(token=token) & Q(owner__token=owner))
            return Response("routine  deleted")
        except:return Response("no such routine found")

apps/routine/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

import uuid

from routine.models import Routine
from routine.forms import RoutineForm


class CreateRoutine(LoginRequiredMixin, FormView):
    '''
        Create a new routine
    '''
    template_name = "routine/create_routine.html"
    form_class = RoutineForm

    def form_valid(self, form):
        form = form.save(commit=False)
        form.owner = self.request.user
        form.token = uuid.uuid4().hex.upper()[0:12]
        form.save()
        return redirect("routine:routine_list")


class UpdateRoutine(LoginRequiredMixin, UpdateView):
    '''
        Update a Routine
    '''
    template_name = 'routine/update_routine.html'
    fields = ["title", "detail", "time", "repeat"]
    success_url = reverse_lazy('routine:routine_list')

    def get_object(self):
        return get_object_or_404(Routine, token=self.kwargs['token'],
                                 owner=self.request.user)


class DeleteRoutine(LoginRequiredMixin, DeleteView):
    '''
        Delete a routine
    '''
    success_url = reverse_lazy('routine:routine_list')
    template_name = "routine/delete_routine.html"

    def get_object(self):
        object = get_object_or_404(Routine, token=self.kwargs['token'],
                                   owner=self.request.user)
        return object


class RoutineList(LoginRequiredMixin, ListView):
    '''
        Routine list
    '''

    template_name = 'routine/routine_list.html'
    paginate_by = 2

    def get_queryset(self):
        return Routine.objects.filter(owner=self.request.user).order_by("time")

apps/routine/templates/routine/create_routine.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Create Routine{% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail | as_crispy_field}}</li><hr>
						        	
					        		<li>{{form.time | as_crispy_field}}</li><hr>
                                    <li>{{form.repeat}}</li><hr>
									</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			

apps/routine/templates/routine/delete_routine.html
{%extends 'base/base.html'%}

{% block title %}Delete Routine{% endblock %}
{% block content %}
				<form method="post">{% csrf_token %}
				    <p >Are you sure you wanna delete this Routine??</p>
				    <input type="submit" value="Delete" class="btn btn-danger">
				</form>

{% endblock %}

apps/routine/templates/routine/routine_list.html
{%extends 'base/base.html'%}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Routine List{% endblock %}
</head>
<body>
    {%block content%}
		<h4>Your routines:</h4>
		{% include 'base/tab.html' %}
			{%for routine in object_list%}
					{{routine.count}}
							<table class="table table-striped table-hover table-bordered">
								<td>
										  <div class="card-body">
											<h5 class="card-title">{{routine.title}}</h5>
											<hr>
											<li>{{routine.detail}}</li>
											<li>{{routine.time}}</li>
											<li>Repeat: {{ routine.get_repeat_display }} </li>
											<li>Repeat: {{ routine.token }} </li>


												<br>
												<a href="{% url 'routine:update_routine' routine.token %}" class="btn btn-outline-secondary btn-sm">Update</a>
												<a href="{%url 'routine:delete_routine' routine.token%}" class="btn btn-outline-danger btn-sm">Delete</a>
										  </div>
								</td>
							</table>
				{% empty %}
					<h4>No routines available... </h4>
					<br><a class="btn btn-secondary" href="{%url 'routine:create_routine'%}">Create new one!</a>

				{%endfor%}
								{% if is_paginated %}
								<hr>
								<nav aria-label="Page navigation example">
									<ul class="pagination justify-content-center pagination-sm">
										{% if page_obj.has_previous %}

										  {% if not search %}
										  <li class="page-item">
											  <a class="page-link" href="{% url 'routine:routine_list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
										  </li>
										  {% else %}
											<li class="page-item">
											  <a class="page-link" href="{% url 'routine:routine_list' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
										  </li>
										  {% endif %}
										{% else %}
										<li class="page-item disabled">
											<a class="page-link" href="#" tabindex="-1">Previous</a>
										</li>
										{% endif %} 
										{% for object in page_obj.paginator.page_range %}
											<li class="page-item"><a class="page-link" href="{% url 'routine:routine_list' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
										{% endfor %} 
										{% if page_obj.has_next %}
										  {% if not search %}
										  <li class="page-item">
											  <a class="page-link" href="{% url 'routine:routine_list' %}?page={{ page_obj.next_page_number }}">Next</a>
										  </li>
										  {% else %}
											<li class="page-item">
											  <a class="page-link" href="{% url 'todo:listRoutine' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
										  </li>
										  {% endif %}
										{% else %}
										<li class="page-item disabled">
											<a class="page-link" href="#">Next</a>
										</li>
										{% endif %}
									</ul>
								</nav>
								{% endif %}
				


    {%endblock%}
</body>
</html>

<tr>
			

apps/routine/templates/routine/update_routine.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Update Routine{% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail|as_crispy_field}}</li><hr>
                                        <li>{{form.time|as_crispy_field}}</li><hr>
                                        <li>{{form.repeat}}</li><hr>
					        		</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
			
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			