apps/project/urls.py
from django.urls import path
from . import views

app_name = "project"

urlpatterns = [
    path("", views.ProjectList.as_view(), name="project_list"),
    path("tasks/<str:token>/", views.ProjectTaskList.as_view(), name="project_task_list"),

    path("update-project/<str:token>/", views.UpdateProject.as_view(),name="update_project"),

    path("create-project/", views.CreateProject.as_view(), name='create_project'),
    path("create-project-task/<str:token>/", views.CreateProjectTask.as_view(), name='create_project_task'),

    path("delete-project/<str:token>/", views.DeleteProject.as_view(),name="delete_project"),

]

apps/task/urls.py
from django.urls import path

from . import  views


app_name = "task"

urlpatterns = [
    path("", views.TaskList.as_view(), name="home"),

    path("update-task/<str:token>/", views.UpdateTask.as_view(), name="update_task"),

    path("create-task/", views.CreateTask.as_view(), name="create_task"),

    path("delete-task/<str:token>/", views.DeleteTask.as_view(),name="delete_task"),
    
    path("search/", views.SearchTask.as_view(), name="search_task"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("account/",include("allauth.urls")),
    path("auth/",include("apps.accounts.urls")),

    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.jwt')),



    path("", include("apps.task.urls")),
    path("routine/", include("apps.routine.urls")),
    path("project/", include("apps.project.urls")),
]

apps/project/models.py
from django.db import models
from task.models import Base, Task


class Project(Base):
    '''Model for creating projects'''

    # tasks of a project
    task = models.ManyToManyField(Task, blank=True, related_name="project_task")

    def __str__(self):
        return self.title

apps/project/forms.py
from django.forms import ModelForm
from project.models import Project
from task.models import Task


class ProjectForm(ModelForm):
	class Meta:
		model = Project
		fields = "__all__"

class ProjectTaskForm(ModelForm):
	class Meta:
		model = Task
		fields = "__all__"

apps/api/v1/views/project_views.py
from django.http import JsonResponse
from rest_framework.response import Response
from django.db.models import Q
from rest_framework.generics import ListAPIView, CreateAPIView
from rest_framework.views import APIView

from api.v1.serializers import ProjectSerializer, ProjectCreateSerializer, ProjectDetailSerializer

import uuid

from task.models import  Task
from project.models import Project
from accounts.models import User

class ProjectView(ListAPIView):
    '''
        Show all projects
    '''
    model = Project
    serializer_class = ProjectSerializer
    def get_queryset(self):
        owner = self.kwargs["owner"]
        object = Project.objects.filter(Q(owner__token=owner))
        return object



class ProjectAdd(CreateAPIView):
    '''
        Create project
    '''
    queryset = Project.objects.all()
    serializer_class = ProjectCreateSerializer
    def create(self,request,owner):
        data = self.request.data
        serializer = ProjectCreateSerializer(data=data, partial=True)
        project_owner = User.objects.get(token=owner)
        if serializer.is_valid():
            serializer = serializer.save(owner=project_owner, token=uuid.uuid4().hex.upper()[0:12])
            return JsonResponse({"token" : serializer.token})
        else:
            return JsonResponse({"error" : "sth is wrong with your information"})

class ProjectDetail(APIView):
    '''
        Project datail
    '''
    queryset = Project.objects.all()
    serializer_class = ProjectDetailSerializer

    def get(self,request,owner,token):
        queryset = Project.objects.filter(Q(token=token) & Q(owner__token=owner))
        serializer = ProjectDetailSerializer(queryset, many=True)
        return Response(serializer.data)

class ProjectDelete(APIView):
    '''
        Delete a project
    '''
    def get(self,request,token,owner):
        try:
            Project.objects.filter(Q(token=token) & Q(owner__token=owner)).delete()
            return Response("project  deleted")
        except:return Response("no such project found")

class ProjectAddTask(APIView):
    '''
        Add task to a project
    '''
    def post(self, request, owner, project_token, task_token):
        try:
            project_model = Project.objects.filter(Q(token= project_token) & Q(owner__token=owner)).first()
            task_model = Task.objects.filter(Q(token= task_token)).first()
            project_model.task.add(task_model)
            return JsonResponse({"done" : "task added to project"})
        except:
            return JsonResponse({"error" : "sth went wrong with your information"})

apps/project/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

import uuid

from task.models import Task
from project.forms import ProjectForm, ProjectTaskForm
from project.models import Project


class CreateProject(LoginRequiredMixin, FormView):
    '''
        Create a new Project
    '''
    template_name = "project/create_project.html"
    form_class = ProjectForm

    def form_valid(self, form):
        form = form.save(commit=False)
        form.owner = self.request.user
        form.token = uuid.uuid4().hex.upper()[0:12]
        form.save()
        return redirect("project:project_list")


class UpdateProject(LoginRequiredMixin, UpdateView):
    '''
        Update a project
    '''
    template_name = 'project/update_project.html'
    fields = ["title", "detail", "time", "status"]
    success_url = reverse_lazy('project:project_list')

    def get_object(self):
        return get_object_or_404(Project, token=self.kwargs['token'],
                                 owner=self.request.user)


class DeleteProject(LoginRequiredMixin, DeleteView):
    '''
        Delete a Project
    '''
    success_url = reverse_lazy('project:project_list')
    template_name = "project/delete_project.html"

    def get_object(self):
        object = get_object_or_404(Project, token=self.kwargs['token'], owner=self.request.user)
        return object

    def post(self, request, *args, **kwargs):
        # Check if there is any task for project to delete

        if (task:=self.get_object().task):
            task.all().delete()
            return super(DeleteProject, self).delete(request, *args, **kwargs)

        return super(DeleteProject, self).delete(request, *args, **kwargs)


class ProjectList(LoginRequiredMixin, ListView):
    '''
        List of a users project
    '''

    template_name = 'project/project_list.html'
    paginate_by = 2

    def get_queryset(self):
        return Project.objects.filter(owner=self.request.user).order_by("status")


class ProjectTaskList(LoginRequiredMixin, ListView):
    '''
        List of task of a Project
    '''
    template_name = 'project/project_task_list.html'

    def get_queryset(self):
        project_token = self.kwargs["token"]
        project = get_object_or_404(Project, token=project_token,
                                    owner=self.request.user)

        return project.task.all()


class CreateProjectTask(LoginRequiredMixin, FormView):
    '''
        This is the page to create a task in a project
    '''
    template_name = 'project/create_project_task.html'
    form_class = ProjectTaskForm

    def form_valid(self, form):
        form = form.save(commit=False)
        project_model = Project.objects.filter(token=self.kwargs['token']).first()
        form.owner = self.request.user
        form.token = uuid.uuid4().hex.upper()[0:12]
        form.save()
        project_model.task.add(form)
        return redirect('project:project_list')

apps/project/templates/project/create_project.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	{% block title %} Create Project {% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail|as_crispy_field}}</li><hr>
										<li>{{form.time | as_crispy_field}}</li><hr>
									</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			

apps/project/templates/project/create_project_task.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} Create Project Task {% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail|as_crispy_field}}</li><hr>
						        	
					        		<li>{{form.time|as_crispy_field}}</li><hr>
									</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			

apps/project/templates/project/delete_project.html
{%extends 'base/base.html'%}

{% block title %} Delete Project {% endblock %}

{% block content %}
				<form method="post">{% csrf_token %}
				    <p >Are you sure you wanna delete this Project??</p>
				    <input type="submit" value="Delete" class="btn btn-danger">
				</form>

{% endblock %}

apps/project/templates/project/project_list.html
{%extends 'base/base.html'%}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}  Project List {% endblock %}
</head>
<body>
    {%block content%}
		<h4>Your Projects:</h4>
		{% include 'base/tab.html' %}

			{%for project in object_list%}
					{{project.count}}
							<table class="table table-striped table-hover table-bordered">
								<td>
										  <div class="card-body">
											<h5 class="card-title">{{project.name}}</h5>
											<hr>
											<li>{{project.detail}}</li>
											<li>{{project.task.count}} Tasks Available</li>
											{%if project.done == False%}
												<li>Status : Unfinished </li>
											{%else%}
												<li>Status : Finished</li>
											{%endif%}
											  <li>Token: {{project.token}} </li>
												<br>
												<a href="{%url 'project:project_task_list' project.token %}" class="btn btn-outline-secondary btn-sm">Tasks</a>
												<a href="{%url 'project:create_project_task' project.token %}" class="btn btn-outline-secondary btn-sm">Add Task</a>
												<a href="{% url 'project:update_project' project.token %}" class="btn btn-outline-secondary btn-sm">Update</a>
												<a href="{%url 'project:delete_project' project.token%}" class="btn btn-outline-danger btn-sm">Delete</a>
										  </div>
								</td>
							</table>
				{% empty %}
					<h4>No Projects available... </h4>
    				<br><a class="btn btn-secondary" href="{%url 'project:create_project'%}">Create new one!</a>
				{%endfor%}

				{% if is_paginated %}
				<hr>
				<nav aria-label="Page navigation example">
					<ul class="pagination justify-content-center pagination-sm">
						{% if page_obj.has_previous %}

						  {% if not search %}
						  <li class="page-item">
							  <a class="page-link" href="{% url 'project:project_list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
						  </li>
						  {% else %}
							<li class="page-item">
							  <a class="page-link" href="{% url 'project:project_list' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
						  </li>
						  {% endif %}
						{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#" tabindex="-1">Previous</a>
						</li>
						{% endif %}
						{% for object in page_obj.paginator.page_range %}
							<li class="page-item"><a class="page-link" href="{% url 'project:project_list' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
						{% endfor %}
						{% if page_obj.has_next %}
						  {% if not search %}
						  <li class="page-item">
							  <a class="page-link" href="{% url 'project:project_list' %}?page={{ page_obj.next_page_number }}">Next</a>
						  </li>
						  {% else %}
							<li class="page-item">
							  <a class="page-link" href="{% url 'project:project_list' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
						  </li>
						  {% endif %}
						{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#">Next</a>
						</li>
						{% endif %}
					</ul>
				</nav>
				{% endif %}

    {%endblock%}
</body>
</html>

<tr>
			

apps/project/templates/project/project_task_list.html
{%extends 'base/base.html'%}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} Project Task Page {% endblock %}
</head>
<body>
    {%block content%}
		<h4>Projects tasks:</h4>

		{%for task in object_list%}
				{{task.count}}
						<table class="table table-striped table-hover table-bordered">
							<td>
									  <div class="card-body">
										<h5 class="card-title">{{task.title}}</h5>
										<hr>
										<li>{{task.detail}}</li>
										{%if not task.status %}
											<li>Status : Unfinished </li>
										{%else%}
											<li>Status : Finished</li>
										{%endif%}
										  <li>Token: {{task.token}}</li>
											<br>
											<a href="{% url 'task:update_task' task.token %}" class="btn btn-outline-secondary btn-sm">Update</a>
											<a href="{% url 'task:delete_task' task.token %}" class="btn btn-outline-danger btn-sm">Delete</a>
									  </div>
							</td>
						</table>
			{% empty %}
				<h4>No tasks Available</h4>
    			<br><a class="btn btn-secondary" href="{% url 'project:create_project_task' view.kwargs.token %}">Create new one!</a> <br>
			{%endfor%}
			<br><a href="{% url 'project:project_list' %}" class="btn btn-outline-secondary btn-sm">Project List</a>

    {%endblock%}
</body>
</html>

<tr>
			

apps/project/templates/project/update_project.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} Update Project {% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail|as_crispy_field}}</li><hr>
                                        <li>{{form.time|as_crispy_field}}</li><hr>
                                        <li>{{form.status|as_crispy_field}}</li><hr>
					        		</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
			
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			