apps/project/urls.py
from django.urls import path
from . import views

app_name = "project"

urlpatterns = [
    path("", views.ProjectList.as_view(), name="project_list"),
    path("tasks/<str:token>/", views.ProjectTaskList.as_view(), name="project_task_list"),

    path("update-project/<str:token>/", views.UpdateProject.as_view(),name="update_project"),

    path("create-project/", views.CreateProject.as_view(), name='create_project'),
    path("create-project-task/<str:token>/", views.CreateProjectTask.as_view(), name='create_project_task'),

    path("delete-project/<str:token>/", views.DeleteProject.as_view(),name="delete_project"),

]

apps/routine/urls.py
from django.urls import  path
from . import  views

app_name = "routine"

urlpatterns = [
    path("", views.RoutineList.as_view(), name="routine_list"),

    path("update-routine/<str:token>/", views.UpdateRoutine.as_view(), name="update_routine"),

    path("create-routine/", views.CreateRoutine.as_view(), name='create_routine'),

    path("delete-routine/<str:token>/", views.DeleteRoutine.as_view(), name="delete_routine"),


]

apps/task/urls.py
from django.urls import path

from . import  views


app_name = "task"

urlpatterns = [
    path("", views.TaskList.as_view(), name="home"),

    path("update-task/<str:token>/", views.UpdateTask.as_view(), name="update_task"),

    path("create-task/", views.CreateTask.as_view(), name="create_task"),

    path("delete-task/<str:token>/", views.DeleteTask.as_view(),name="delete_task"),
    
    path("search/", views.SearchTask.as_view(), name="search_task"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("account/",include("allauth.urls")),
    path("auth/",include("apps.accounts.urls")),

    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.jwt')),



    path("", include("apps.task.urls")),
    path("routine/", include("apps.routine.urls")),
    path("project/", include("apps.project.urls")),
]

apps/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>
      body {background: #f4f4f4;}

    </style>
  </head>
  <body>
  	{% include 'base/navbar.html' %}
    <br/>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    <div class="shadow p-4 mb-5 bg-body rounded">
      {% block content %}
      {% endblock %}
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

apps/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'task:home'%}">Todo List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        </li>

      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
      {% endif %}

      </ul>
        {%if request.user.is_authenticated%}
          <form class="d-flex" method="get" action="{%url 'task:search_task'%}">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Search Tasks" aria-label="Search" name="nav_search">
              <button class="btn btn-outline-secondary" type="submit">Search</button>
          </form>
      {%endif%}

    </div>
  </div>
</nav>

apps/templates/base/tab.html
<ul class="nav nav-tabs">
			<li class="nav-item">
			  <a class="nav-link"  href="{%url 'task:home'%}">Tasks</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" aria-current="page" href="{% url 'project:project_list' %}">Projects</a>
			</li>
            <li class="nav-item">
				<a class="nav-link" aria-current="page" href="{%url 'routine:routine_list' %}">Routine</a>
            </li>
</ul>