apps/task/urls.py
from django.urls import path

from . import  views


app_name = "task"

urlpatterns = [
    path("", views.TaskList.as_view(), name="home"),

    path("update-task/<str:token>/", views.UpdateTask.as_view(), name="update_task"),

    path("create-task/", views.CreateTask.as_view(), name="create_task"),

    path("delete-task/<str:token>/", views.DeleteTask.as_view(),name="delete_task"),
    
    path("search/", views.SearchTask.as_view(), name="search_task"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("account/",include("allauth.urls")),
    path("auth/",include("apps.accounts.urls")),

    path("api/v1/",include("apps.api.v1.urls")),
    path("api/v2/",include("apps.api.v2.urls")),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.jwt')),



    path("", include("apps.task.urls")),
    path("routine/", include("apps.routine.urls")),
    path("project/", include("apps.project.urls")),
]

apps/task/models.py
from django.db import models
from accounts.models import User


class Base(models.Model):
    '''Common fields of Task, Routine and Project model'''

    title = models.CharField(max_length=120)
    detail = models.TextField()

    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    token = models.CharField(max_length=12, unique=True, blank=True, null=True)

    time = models.TimeField()

    status = models.BooleanField(default=False)

    class Meta:
        abstract = True



class Task(Base):
    '''Task model'''

    def __str__(self):
        return self.title

apps/task/forms.py
from django import forms
from django.forms import ModelForm
from .models import Task

class TodoForm(ModelForm):
	class Meta:
		model = Task
		fields = "__all__"

apps/api/v1/views/task_views.py
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.db.models import Q
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, ListAPIView
from rest_framework.response import Response

import uuid

from api.v1.serializers import TaskSerializer, TaskCreateSerializer, TaskDetailSerializer
from task.models import Task
from accounts.models import User

class TaskView(ListAPIView):
    '''
        Show all tasks
    '''
    model = Task
    serializer_class = TaskSerializer
    def get_queryset(self):
        owner = self.kwargs["owner"]
        object = Task.objects.filter(Q(owner__token=owner))
        return object

class TaskAdd(CreateAPIView):
    '''
        Create task
    '''
    queryset = Task.objects.all()
    serializer_class = TaskCreateSerializer
    def create(self,request,owner):
        data = self.request.data
        serializer = TaskCreateSerializer(data=data, partial=True)
        task_owner = User.objects.get(token=owner)
        if serializer.is_valid():
            serializer = serializer.save(owner=task_owner,token=uuid.uuid4().hex.upper()[0:12])
            return JsonResponse({"token" : serializer.token})
        else:
            return JsonResponse({"error" : "sth is wrong with your information"})

class TaskDetail(APIView):
    '''
        Your tasks detail
    '''
    queryset = Task.objects.all()
    serializer_class = TaskCreateSerializer
    def get(self,request,owner,token):
        queryset = Task.objects.filter(Q(token=token) & Q(owner__token=owner))
        serializer = TaskDetailSerializer(queryset, many=True)
        return Response(serializer.data)

class TaskDelete(APIView):
    '''
        Delete a task
    '''
    def get(self,request,token,owner):
        try:
            Task.objects.filter(Q(token=token) & Q(owner__token=owner)).delete()
            return Response("Task  deleted")
        except:return Response("no such task found")

class TaskAutoDelete(APIView):
    '''
        Remove done tasks
    '''
    def get(self,request,owner):
            obj = get_object_or_404(task, Q(owner__token=owner) & Q(done=True))
            obj.delete()
            return Response("some tasks removed")


def TaskUpdateStatus(request, token, owner):
    object = Task.objects.filter(Q(token=token) & Q(owner__token=owner)).first()
    if object.done is not True:
        object.done = True
        object.save()
        return JsonResponse({'done': 'Task updated successfully'}, status=200)
    else:
        return JsonResponse({'error': 'Task is already done'}, status=401)

apps/task/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q

import uuid

from task.models import Task
from task.forms import TodoForm



class TaskList(LoginRequiredMixin, ListView):
    '''
        List of all tasks
    '''

    template_name = 'task/task_list.html'
    paginate_by = 2
    context_object_name = "tasks"

    def get_queryset(self):
        return Task.objects.filter(
            owner=self.request.user
        ).order_by("time", "status")


class CreateTask(LoginRequiredMixin, FormView):
    '''
        Create a new task
    '''

    template_name = 'task/create_task.html'
    form_class = TodoForm
    success_url = 'task:home'

    def form_valid(self, form):
        form = form.save(commit=False)
        form.owner = self.request.user
        form.token = uuid.uuid4().hex.upper()[0:12]
        form.save()
        return redirect('task:home')



class UpdateTask(LoginRequiredMixin, UpdateView):
    '''
        Update a task
    '''

    template_name = 'task/update_task.html'
    fields = ["title", "detail", "time", "status"]
    success_url = reverse_lazy('task:home')

    def get_object(self):
        return get_object_or_404(Task, token=self.kwargs['token'],
                                 owner=self.request.user)



class DeleteTask(LoginRequiredMixin, DeleteView):
    '''
        Delete a task
    '''

    model = Task
    success_url = reverse_lazy('task:home')
    template_name = "task/delete_task.html"

    def get_object(self):
        return get_object_or_404(Task, token=self.kwargs["token"],
                                 owner=self.request.user)


class SearchTask(ListView):
    model = Task
    template_name = "base/task_list.html"
    context_object_name = "task"

    def get_queryset(self):
        query = self.request.GET.get("nav_search")

        object = Task.objects.filter(Q(title__icontains=query)
                                          & Q(owner=self.request.user))

        return object

apps/task/templates/task/create_task.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Create Task{% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail|as_crispy_field}}</li><hr>
						        	
					        		<li>{{form.time|as_crispy_field}}</li><hr>
									</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			

apps/task/templates/task/delete_task.html
{%extends 'base/base.html'%}

{% block title %}Delete Task {% endblock %}

{% block content %}
			{% if request.user == task.owner %}
				<form method="post">{% csrf_token %}
				    <p >Are you sure you wanna delete this Task??</p>
				    <input type="submit" value="Delete" class="btn btn-danger">
				</form>
			{%else%}
				<h1>Permission Denied</h1>
			{%endif	%}

{% endblock %}

apps/task/templates/task/task_list.html
{%extends 'base/base.html'%}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Task List{% endblock %}
</head>
<body>
    {%block content%}

		<h4>Your Tasks:</h4>
		{% include 'base/tab.html' %}
		    	{%for task in object_list%}

						<table class="table table-striped table-hover table-bordered">
							<td>
									  <div class="card-body">
										<h5 class="card-title">{{ task.name }}</h5>
										<hr>
										<li>{{ task.detail }}</li>
										<li>time: {{task.time|naturaltime }}</li>
										{% if not task.status %}
											<li>Status : Unfinished </li>
										{% else %}
											<li>Status : Done</li>
										{% endif %}

										  <li>Token: {{ task.token }}</li>
											<br>
											<a href="{% url 'task:update_task' task.token %}" class="btn btn-outline-secondary btn-sm">Datail</a>
											<a href="{%url 'task:delete_task'  task.token %}" class="btn btn-outline-danger btn-sm">Delete</a>
									  </div>
							</td>
						</table>
					{% empty %}
						<h4>No tasks available... </h4>
    					<br><a class="btn btn-secondary" href="{%url 'task:create_task'%}">Create new one!</a>
					{%endfor%}
								{% if is_paginated %}
								<hr>
								<nav aria-label="Page navigation example">
									<ul class="pagination justify-content-center pagination-sm">
										{% if page_obj.has_previous %}

										  {% if not search %}
										  <li class="page-item">
											  <a class="page-link" href="{% url 'task:home' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
										  </li>
										  {% else %}
											<li class="page-item">
											  <a class="page-link" href="{% url 'task:home' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
										  </li>
										  {% endif %}
										{% else %}
										<li class="page-item disabled">
											<a class="page-link" href="#" tabindex="-1">Previous</a>
										</li>
										{% endif %} 
										{% for object in page_obj.paginator.page_range %}
											<li class="page-item"><a class="page-link" href="{% url 'task:home' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
										{% endfor %} 
										{% if page_obj.has_next %}
										  {% if not search %}
										  <li class="page-item">
											  <a class="page-link" href="{% url 'task:home' %}?page={{ page_obj.next_page_number }}">Next</a>
										  </li>
										  {% else %}
											<li class="page-item">
											  <a class="page-link" href="{% url 'task:home' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
										  </li>
										  {% endif %}
										{% else %}
										<li class="page-item disabled">
											<a class="page-link" href="#">Next</a>
										</li>
										{% endif %}
									</ul>
								</nav>
								{% endif %}
				


    {%endblock%}
</body>
</html>

<tr>
			

apps/task/templates/task/update_task.html
{%extends 'base/base.html'%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Update Task{% endblock %}
</head>
<body>
    {%block content%}
			    	<form method="POST" action="">
			    		{%csrf_token%}
			    		<table class="table table-striped table-hover table-bordered">
				        <td>
				        		  <div class="card-body">
					        		<h5 class="card-title">{{form.title|as_crispy_field}}</h5>
					        		<hr>
					        		<div class="mb-3">
						        		<li>{{form.detail|as_crispy_field}}</li><hr>
						        	
					        		<li>{{form.time|as_crispy_field}}</li><hr>
				
					        		<li>{{form.status|as_crispy_field}}</li><hr>
					        		</div>
					        		<br>
					        		<button  class="btn btn-outline-success btn-sm">Save</button>
								</div>
						</td>
					</table>
			    	</form>
			
	    <br>
    {%endblock%}
</body>
</html>

<tr>
			